version: '3.4'

services:
    app:
        build:
            context: 'docker/php-cli'
            args:
                APP_UID: '${UID:-1000}'
                APP_GID: '${GID:-1000}'
        environment:
            DB_HOST: 'db'
        depends_on:
            - 'db'
        volumes:
            - '.:/app'
            - 'composer-cache:/composer/cache'

    db:
        image: 'mariadb:10.6'
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: '!root'
            MYSQL_DATABASE: 'tests'
            MYSQL_USER: 'tests'
            MYSQL_PASSWORD: 'tests'
        volumes:
            - 'db-data:/var/lib/mysql'
            - './docker/db-data:/docker-entrypoint-initdb.d'

volumes:
    composer-cache:
    db-data:
